env:
  browser: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'plugin:no-jquery/deprecated'
plugins:
  - no-jquery
parserOptions:
  ecmaVersion: 2019
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
