require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.2
  NewCops: enable
  ActiveSupportExtensionsEnabled: true

Rails:
  Enabled: true

Minitest/MultipleAssertions:
  Max: 15
  Enabled: true

Minitest/AssertPredicate:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 25

Style/ExpandPathArguments:
  Enabled: true
  Exclude:
    - test/**/*

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Rails/ContentTag:
  Enabled: true
  Exclude:
    - app/helpers/additional_tags_issues_helper.rb

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - '/**/*.rsb'

Style/SuperWithArgsParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OptionHash:
  Enabled: true
  SuspiciousParamNames:
    - options
    - api_options
    - opts
    - args
    - params
    - parameters
    - settings

# postgresql and mysql are supported
# autodetect does not work without database configuration
Rails/BulkChangeTable:
  Enabled: true
  Database: postgresql

Style/ReturnNil:
  Enabled: true

Style/UnlessLogicalOperators:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  EnforcedStyle: omit_parentheses

Naming/VariableNumber:
  Enabled: true
  Exclude:
    - 'test/**/*'

Layout/LineContinuationLeadingSpace:
  Enabled: false

# see https://github.com/rubocop/rubocop-rails/issues/578
# redmine does not use load_defaults: https://rails.rubystyle.guide/#config-defaults
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# does not work with redirect_to or ensure
Rails/ActionControllerFlashBeforeRender:
  Enabled: false

Bundler/DuplicatedGroup:
  Enabled: false
